import {readdir,readFile,writeFile,mkdir,access} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const source=path.join(root,'src'),destination=path.join(root,'public/fonts');
await mkdir(destination,{recursive:true});
const files=(await readdir(source,{recursive:true})).filter(f=>/\.(astro|ts|json)$/.test(f));
const text=(await Promise.all(files.map(f=>readFile(path.join(source,f),'utf8')))).join('');
const chinese=[...new Set([...text].filter(c=>c.codePointAt(0)>0x2e7f))].sort();
const latin=[...new Set([...Array.from({length:95},(_,i)=>String.fromCodePoint(i+32)),...[...text].filter(c=>c.codePointAt(0)>126&&c.codePointAt(0)<0x2e80)])].sort();
// Retry interrupted font downloads without falling back to a system font.
const fetchFont=async(url,options)=>{
 for(let attempt=0;attempt<3;attempt++){
  try{return await fetch(url,options);}catch(error){if(attempt===2)throw error;await new Promise(resolve=>setTimeout(resolve,600*(attempt+1)));}
 }
};
const tasks=[];
for(let i=0;i<chinese.length;i+=220)tasks.push({query:'Noto Sans SC',family:'Studio Sans',file:`noto-${i/220}`,chars:chinese.slice(i,i+220)});
tasks.push({query:'Manrope',family:'Studio Manrope',file:'manrope',chars:latin});
const css=await Promise.all(tasks.map(async task=>{
 const request=new URL('https://fonts.googleapis.com/css2');request.searchParams.set('family',`${task.query}:wght@400..500`);request.searchParams.set('display','swap');request.searchParams.set('text',task.chars.join(''));
 const response=await fetchFont(request,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'}});
 if(!response.ok)throw new Error(`Font CSS ${task.file}: ${response.status}`);
 let result=await response.text();const urls=[...new Set([...result.matchAll(/url\((https:[^)]+)\)/g)].map(m=>m[1]))];
 if(!urls.length)throw new Error('Missing font URLs');
 for(let i=0;i<urls.length;i++){
  const resource=await fetchFont(urls[i]);if(!resource.ok)throw new Error(`Font file: ${resource.status}`);
  const bytes=Buffer.from(await resource.arrayBuffer()),signature=bytes.subarray(0,4).toString();
  const extension=signature==='wOF2'?'woff2':signature==='wOFF'?'woff':'ttf';
  const name=`${task.file}-${i}.${extension}`;await writeFile(path.join(destination,name),bytes);result=result.replaceAll(urls[i],`/fonts/${name}`);
 }
 const unicode=task.chars.map(c=>`U+${c.codePointAt(0).toString(16)}`).join(',');
 return result.replace(/unicode-range:[^;]+;/g,'').replaceAll(`'${task.query}'`,`'${task.family}'`).replaceAll('}',`unicode-range:${unicode};\n}`);
}));
await writeFile(path.join(source,'styles/fonts.css'),'/* Generated by npm run fonts:prepare. Font licenses live in public/fonts. */\n'+css.join('\n'));
await writeFile(path.join(destination,'coverage.json'),JSON.stringify({chinese:chinese.join(''),latin:latin.join('')},null,2));
for(const [name,url] of [['noto-sans-sc','https://raw.githubusercontent.com/google/fonts/main/ofl/notosanssc/OFL.txt'],['manrope','https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/OFL.txt']]){
 const license=path.join(destination,`${name}-OFL.txt`);
 try{await access(license);}catch{const response=await fetchFont(url);if(!response.ok)throw new Error(`Font license: ${response.status}`);await writeFile(license,await response.text());}
}
console.log(`Prepared local fonts: ${chinese.length} CJK characters, ${latin.length} Latin/symbol characters, ${tasks.length} subsets.`);
